#!/bin/bash
P=`dirname $0`
ARGS=$@

if [ -f $P/obj/main.native ]; then
  CMD=$P/obj/main.native
elif [ -f $P/obj/main.d.byte ]; then
  CMD=$P/obj/main.d.byte
else
  echo "Compile first"
  exit 100
fi


if [[ $VERBOSE == "true" ]]; then
  echo "$CMD $ARGS"
fi

$CMD $ARGS
