#!/bin/sh
P=`dirname $0`
if [ -f $P/build/main.native ]; then
  $P/build/main.native $@
elif [ -f $P/build/main.d.byte ]; then
  $P/build/main.d.byte $@
else
  echo "Compile Typed JavaScript first (make or make opt)"
  exit 50
fi
  
