#!/bin/bash
P=`dirname $0`
if [ -f $P/obj/main.native ]; then
  $P/obj/main.native $@
elif [ -f $P/obj/main.p.native ]; then
  $P/obj/main.p.native $@
elif [ -f $P/obj/main.d.byte ]; then
  $P/obj/main.d.byte $@
else
  echo "Compile first"
  exit 100
fi
  
