#!/bin/bash
P=`dirname $0`
$P/run -contracts \
  -env $P/data/javascript.env \
  -idl $P/data/dom.idl \
  -idl $P/data/window.idl \
  -idl $P/data/html.idl \
  -idl $P/data/views.idl \
  -idl $P/data/xmlhttprequest.idl \
  -idl $P/data/events.idl \
  -global HTMLWindow \
  $@
