function ig_a(a){throw a;}var ig_b=true,ig_=null,ig_c=false,ig_d;function ig_e(a){var b=window;if(a!="")for(a=a.split(".");a.length;){var c=a.shift();if(typeof b[c]!="object")b[c]={};b=b[c]}return b}(function(){function a(c,d){c=ig_e(c);for(var e=0;e<d.length;e+=2)c[d[e]]=d[e+1]}function b(c,d,e,f,h){if(f)for(var g=0;g<f.length;g+=2)e.prototype[f[g]]=f[g+1];if(h)for(g=0;g<h.length;g+=2)e[h[g]]=h[g+1];a(c,[d,e])}a("",["_exportSymbols",a]);a("",["_exportClass",b])})();function ig_f(a,b,c){if(!a.className)return ig_c;for(var d=a.className.split(" "),e=[],f=ig_c,h=0;h<d.length;++h)if(d[h]!=b)e.push(d[h]);else{f=ig_b;c&&e.push(c)}a.className=e.join(" ");return f};function ig_g(a){a=a||document.location.href;var b=a.indexOf("?");if(b==-1)return"";var c=a.indexOf("#");a=c==-1?a.substr(b+1):a.substr(b+1,c-b-1)+"&"+a.substr(c+1);return a.split("&")}function _esc(a){return window.encodeURIComponent?encodeURIComponent(a):escape(a)}function _unesc(a){return window.decodeURIComponent?decodeURIComponent(a):unescape(a)}
function _argsUrl(a){var b={};a=ig_g(a);for(var c=0;c<a.length;c++){var d=a[c].indexOf("=");if(d!=-1){var e=a[c].substring(0,d);d=a[c].substring(d+1);d=d.replace(/\+/g," ");b[e]=_unesc(d)}}return b};var ig_aa={domload:1,xsetpdone:1,moduleedit:1,modulesocialedit:1,modulecanceledit:1,moduledelete:1,moduleundelete:1,modulezip:1,moduleunzip:1,modulemaximize:1,moduleunmaximize:1,moduledragstart:1,moduledragend:1,moduletitleclick:1,load:1,unload:1,resize:1},ig_h={},ig_ba={dragstart:1,dragend:1,titleclick:1,edit:1,socialedit:1,canceledit:1,"delete":1,undelete:1,zip:1,unzip:1,maximize:1,unmaximize:1};
function ig_ca(a){if(a.hasOwnProperty&&a.hasOwnProperty("ig_event_hashcode_"))return a.ig_event_hashcode_;a.ig_event_hashcode_||(a.ig_event_hashcode_=++ig_i.ue);return a.ig_event_hashcode_}function ig_da(a){return"builtin_"+a}function ig_ea(a,b){if(a.indexOf&&a.indexOf("m_")==0)a=a.substring(2);return"builtin_m"+a+"_"+b}function ig_fa(a,b){return"builtin_"+ig_i.fe(a)+"_"+b}function ig_ga(a){return"custom_"+a}
function ig_ha(){for(var a in ig_i.c){for(var b=0;b<ig_i.c[a].length;b++)delete ig_i.c[a][b];if(a in ig_i.oa){var c=ig_i.oa[a];b=c[0];var d=c[1];c=c[2];if(b.removeEventListener)b.removeEventListener(d,c,ig_c);else b.detachEvent&&b.detachEvent("on"+d,c);delete ig_i.oa[a]}}ig_h={}}function ig_ia(a,b,c){for(c=c;c<b.length;c++)a[a.length]=b[c];return a}function ig_ja(a,b){if(a in ig_i.c)for(var c=0;c<ig_i.c[a].length;c++)if(ig_i.c[a][c]===b){ig_i.c[a][c]=ig_;return ig_b}return ig_c}
function ig_ka(a){if(a in ig_i.c)for(var b=0;b<ig_i.c[a].length;b++)if(ig_i.c[a][b]){for(var c=[],d=1;d<arguments.length;d++)c[c.length]=arguments[d];ig_i.c[a][b].apply(this,c)}}function ig_la(a,b){if(!(a in ig_i.Mf))ig_a(Error("Unsupported event type: "+a));a=ig_i.Wa(a);a in ig_i.c||(ig_i.c[a]=[]);ig_i.c[a][ig_i.c[a].length]=b;return ig_i.c[a].length}
function ig_ma(a,b,c){if(!(b in ig_i.Nf))ig_a(Error("Unsupported module event type: "+b));a=ig_i.Xa(a,b);a in ig_i.c||(ig_i.c[a]=[]);ig_i.c[a][ig_i.c[a].length]=c}
function ig_na(a,b,c){var d=ig_i.Ub(a,b);if(!(d in ig_i.c)){ig_i.c[d]=[];var e=function(f){if(!f)f=window.event;ig_i.Fa.apply(a,[d,f])};if(a.addEventListener)a.addEventListener(b,e,ig_c);else if(a.attachEvent)a.attachEvent("on"+b,e);else ig_a(Error("Object {"+a+"} does not support DOM events."));ig_i.oa[d]=[a,b,e]}e=ig_i.c[d].length;if(a===window&&b=="unload"&&e>0){ig_i.c[d][e]=ig_i.c[d][e-1];ig_i.c[d][e-1]=c}else if(ig_h[b])setTimeout(c,10);else ig_i.c[d][e]=c}
function ig_oa(a,b){a=ig_i.Va(a);a in ig_i.c||(ig_i.c[a]=[]);ig_i.c[a][ig_i.c[a].length]=b}function ig_pa(a,b){a=ig_i.Wa(a);return ig_i.Ca(a,b)}function ig_qa(a,b,c){a=ig_i.Xa(a,b);return ig_i.Ca(a,c)}function ig_ra(a,b,c){a=ig_i.Ub(a,b);return ig_i.Ca(a,c)}function ig_sa(a,b){a=ig_i.Va(a);return ig_i.Ca(a,b)}
function ig_ta(a){var b=a=="load"||a=="domload",c=ig_c;if(b){(c=ig_h[a])||_IG_TriggerCustomEvent(a+"_start");ig_h[a]=ig_b}var d=ig_i.R([ig_i.Wa(a)],arguments,1);ig_i.Fa.apply(window,d);b&&!c&&_IG_TriggerCustomEvent(a+"_end")}function ig_ua(){var a=ig_i.R([],arguments,0);setTimeout(function(){ig_i.cd.apply(window,a)},0)}function ig_va(a,b){var c=ig_i.R([ig_i.Xa(a,b)],arguments,2);ig_i.Fa.apply(window,c)}
function ig_wa(){var a=ig_i.R([],arguments,0);setTimeout(function(){ig_i.yb.apply(window,a)},0)}function ig_xa(a){var b=ig_i.R([ig_i.Va(a)],arguments,1);ig_i.Fa.apply(window,b)}function ig_ya(){var a=ig_i.R([],arguments,0);setTimeout(function(){ig_i.ad.apply(window,a)},0)}function ig_j(a,b){switch(a){case "delete":case "undelete":case "edit":case "socialedit":case "canceledit":case "zip":case "unzip":case "maximize":case "unmaximize":ig_wa(b,a);ig_ua("module"+a,b);break}}
function _IG_delayScript(a,b){function c(){clearTimeout(d);_IG_RemoveEventHandler("load",c);setTimeout(a,0)}var d;b=!isNaN(b)&&b||1E4;d=setTimeout(c,b);_IG_AddEventHandler("load",c)}
var ig_i={ue:0,c:{},oa:{},Mf:ig_aa,Nf:ig_ba,fe:ig_ca,Wa:ig_da,Xa:ig_ea,Ub:ig_fa,Va:ig_ga,Pd:ig_ha,R:ig_ia,Ca:ig_ja,Fa:ig_ka,sd:ig_la,Ob:ig_ma,rd:ig_na,qd:ig_oa,jf:ig_pa,Oc:ig_qa,gf:ig_ra,ff:ig_sa,cd:ig_ta,yb:ig_va,ad:ig_xa,Uf:ig_ua,bd:ig_wa,Tf:ig_ya},_IG_AddEventHandler=ig_i.sd,_IG_AddModuleEventHandler=ig_i.Ob,_IG_AddGadgetEventHandler=ig_i.Ob,_IG_AddDOMEventHandler=ig_i.rd,_IG_AddCustomEventHandler=ig_i.qd,_IG_RemoveEventHandler=ig_i.jf,_IG_RemoveModuleEventHandler=ig_i.Oc,_IG_RemoveGadgetEventHandler=
ig_i.Oc,_IG_RemoveDOMEventHandler=ig_i.gf,_IG_RemoveCustomEventHandler=ig_i.ff,_IG_TriggerEvent=ig_i.cd,_IG_TriggerModuleEvent=ig_i.yb,_IG_TriggerGadgetEvent=ig_i.yb,_IG_TriggerCustomEvent=ig_i.ad,_IG_TriggerDelayedEvent=ig_i.Uf,_IG_TriggerDelayedModuleEvent=ig_i.bd,_IG_TriggerDelayedGadgetEvent=ig_i.bd,_IG_TriggerDelayedCustomEvent=ig_i.Tf;_IG_AddDOMEventHandler(window,"unload",ig_i.Pd);_IG_AddDOMEventHandler(window,"load",function(){_IG_TriggerEvent("load")});
_IG_AddDOMEventHandler(window,"unload",function(){_IG_TriggerEvent("unload")});_IG_AddDOMEventHandler(window,"resize",function(){_IG_TriggerEvent("resize")});function _IG_RegisterOnloadHandler(a){_IG_AddEventHandler("domload",a)}function _IG_LoadLibraryDeferred(a,b){_IG_RegisterOnloadHandler(function(){_IG_LoadScript(a,b)})}_exportSymbols("google.gadgets.Events",["addHandler",_IG_AddEventHandler,"removeHandler",_IG_RemoveEventHandler,"addOnloadHandler",_IG_RegisterOnloadHandler]);
function _IG_RegisterMaximizeHandler(a,b){_IG_AddModuleEventHandler(a,"unmaximize",function(){b(ig_c)});_IG_AddModuleEventHandler(a,"maximize",function(){b(ig_b)})};function ig_k(a,b){function c(){}c.prototype=a.prototype;b.prototype=new c}function _gel(a){return document.getElementById(a)}function _gelstn(a,b){b=b||document;if(a=="*"&&b.all)return b.all;return b.getElementsByTagName?b.getElementsByTagName(a):[]}function _gelsbyregex(a,b,c){a=_gelstn(a,c);c=[];for(var d=0,e;e=a[d];++d)b.test(e.id)&&c.push(e);return c}function _uc(a){return a.toUpperCase()}function _trim(a){return a.replace(/^\s*|\s*$/g,"")}
function _jesc(a){return a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/"/g,'\\"')}function _toggle(a){if(a)if(a.style.display==""||a.style.display=="block")a.style.display="none";else if(a.style.display=="none")a.style.display="block"}function _hesc(a){return a.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function _striptags(a){return a.replace(/<\/?[^>]+>/gi,"")}function _ig_gmid_(a){return a.split("_")[2]}
function _showUserPrefs(a,b){if(b){ig_l("m_"+a+"_editbox","none");ig_l("m_"+a+"_aclbox","block");ig_j("socialedit","m_"+a)}else{ig_l("m_"+a+"_editbox","");ig_l("m_"+a+"_aclbox","none");ig_j("edit","m_"+a)}if(a=_gel("m_"+a))a.className="modbox_e"}function _closeUserPrefs(a){ig_l("m_"+a+"_editbox","none");ig_l("m_"+a+"_aclbox","none");if(a=_gel("m_"+a))a.className="modbox"}function _min(a,b){return a<b?a:b}function _max(a,b){return a>b?a:b}
function _IG_LoadScript(a,b){_sendx(a,function(c){window.eval(c);eval(b)})}function _IG_LoadScriptCallback(a,b){_sendx(a,function(c){window.eval(c);b&&b()})}function _IG_LoadScriptXDomain(a,b,c){function d(){eval(b)?c():setTimeout(function(){d()},100)}var e=document.createElement("script");e.src=a;_gelstn("head")[0].appendChild(e);b&&d()}
function _IG_LoadCss(a){var b=_gelstn("head")[0];if(!b)ig_a(new Error("Document is missing <head> element.  Failed to load CSS."));var c=document.createElement("style");c.type="text/css";if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));b.insertBefore(c,b.firstChild)}function _log(a){a="/ig/log?msg="+_esc(a);_sendx(a)}
function _sendx(a,b,c,d){var e=ig_m();e.open(d?"POST":"GET",a,ig_b);if(b)e.onreadystatechange=function(){if(e.readyState==4)b(c&&e.responseXML?e.responseXML:e.responseText)};e.send(d||ig_)}function ig_m(){var a=ig_;if(window.ActiveXObject)(a=new ActiveXObject("Msxml2.XMLHTTP"))||(a=new ActiveXObject("Microsoft.XMLHTTP"));else if(window.XMLHttpRequest)a=new XMLHttpRequest;return a}
var _et="",_brand="",_bmod="",_source="",_ae="",_pid="",_authpath="",_prefid="",_setp_url="/ig/setp",_hl="",_old_html=ig_b,_use_old_feed_styles=ig_b,ig_n=ig_,ig_o=ig_;function ig_p(a,b,c){var d=a.elements[b];if(d)d.value=c;else{d=document.createElement("input");d.type="hidden";d.name=b;d.value=c;a.appendChild(d)}}function _args(){return _argsUrl(document.location.href)}function _IG_isIE(){return/msie/i.test(navigator.userAgent)}
function _qs(a){var b={pid:1,host:1,gl:1,hl:1,enable_flag:1,e:1,expid:1};a=a||_args();var c=["?"];for(var d in a)b[d]&&c.push(d,"=",_esc(a[d]),"&");return c.join("")}var ig_za=/^([^?#]+)(?:\?([^#]*))?(#.*)?/;function ig_q(a,b){a=ig_za.exec(a);var c=[a[1],"?",a[2]];c.push(a[2]?"&":"",b.join("&"),a[3]);return c.join("")}function ig_Aa(a){var b={url:document.location,et:_et,brand:_brand,bmod:_bmod,source:_source,ae:_ae,pid:_pid,ap:_authpath,prefid:_prefid};for(var c in b)b[c]&&ig_p(a,c,b[c])}
function _submit_form(a,b){a.action=_setp_url+_qs()+b;a.method="get";ig_Aa(a);a.submit()}function _fsetp(a,b,c){a.action=_setp_url;a.method="get";ig_Aa(a);ig_p(a,"m_"+b+"_t",c);c=_args();b=c.host;c=c.hl;b&&ig_p(a,"host",b);c&&ig_p(a,"hl",c);return ig_b}var ig_r=[],ig_s=ig_c;
function ig_Ba(){var a;a=[["et",_et],["pid",_pid],["ap",_authpath],["brand",_brand],["bmod",_bmod],["source",_source],["ae",_ae],["prefid",_prefid]];for(var b=[],c=0;c<a.length;++c)if(a[c].length==2){var d=a[c][0],e=a[c][1];e!=ig_&&e!=""&&b.push(d+"="+e)}return a=b.join("&")}function ig_Ca(){if(ig_r.length==0)ig_s=ig_c;else{ig_s=ig_b;var a=_setp_url+_qs()+ig_Ba(),b=ig_r.join("&");ig_r=[];var c=a.length+b.length>=1800;if(c)_sendx(a,ig_Da,ig_c,b);else{a+="&"+b;_sendx(a,ig_Da,ig_c,ig_)}}}
function ig_Da(){_IG_TriggerDelayedEvent("xsetpdone");ig_Ca()}function _xsetp(a){ig_r.push(a);ig_s||ig_Ca()}function _xsetp_is_done(){return ig_r.length==0&&ig_s==ig_c}function _dlsetp(a,b){b||(b=_esc(document.location));document.location=_setp_url+_qs()+ig_Ba()+"&url="+b+"&"+a}function _removeTabParam(a){a=a.split("#");a[0]=a[0].replace(/([?&])t=[^&#]*([&#]|$)/g,"$1");a[0]=a[0].replace(/[?&]$/,"");return a.join("#")}function _select_tab(a,b){b=b||"/ig";ig_t(b+_qs()+"t="+a)}
function _select_tab_and_log(a,b){_sendx("/ig/ui?xp=v2&action=selectTab&t="+a);_select_tab(a,b)}function _select_gadget_and_log(a,b){_sendx("/ig/ui?xp=v2&action=maximizeMod&from=selectMod&mid="+b);window.nd?ig_t("/ig"+_qs()+"t="+a+"&g="+b):ig_t("/ig"+_qs()+"t="+a+"#max"+b)}function ig_t(a){window.location.href=a}function ig_l(a,b){if(a=_gel(a))a.style.display=b}_exportSymbols("",["setDisplayStyle",ig_l]);
function _ssbc(a,b,c){for(var d=_gelstn("*"),e=0,f;f=d[e];e++)if(f.className==a)f.style[b]=c}function _findPos(a){for(var b=0,c=0;a!=ig_;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return[b,c]}function _getGadgetContainer(a){var b=_gel("m_"+a+"_b");if(!b){b=_gel("remote_"+a);if(!b)b=document.body}return b}function _appendMaxAgeParameter(a,b){var c=/[?&]$/.test(a);return a+(c?"":"&")+"max_age="+b+(c?"&":"")}
function _getStyle(a,b){if(typeof a.currentStyle!="undefined")a=a.currentStyle;else if(document.defaultView.getComputedStyle!="undefined")a=document.defaultView.getComputedStyle(a,ig_);else return"";return a[b]}function ig_u(){for(var a=_IG_MD,b=0;b<arguments.length;++b){a=a[arguments[b]];if(a==ig_)return ig_}return a}function _bidi_span_wrap(a,b){return _bidi_span_wrap_html(_hesc(a),b)}
function _bidi_span_wrap_html(a,b){if(b=="rtl")return"<span dir=rtl>"+a+"</span>&lrm;";return a}
function _bidi_unicode_wrap(a,b){if(b=="rtl")return"\u202b"+a+"\u202c\u200e";return a}_exportSymbols("google.gadgets.Util",["args",_args]);_exportSymbols("",["addParamPairsToUrl",ig_q,"xmlhttp",ig_m]);if(!window.FLAG_isInSplitJS)window.FLAG_isInSplitJS=ig_c;function ig_v(a){this.A=[];this.jb=a;this.ta("_IG_DD_open");this.ta("_IG_hoverHeader");this.ta("_IG_hoverModule");this.O("_IG_DD_create");this.O("_IG_DD_init");this.O("_IG_initDrag");this.O("_IG_PushHistory");this.O("_IG_PU_MakeDialogButton")}ig_v.prototype.Mc=ig_c;ig_v.prototype.cc=ig_c;ig_v.jd=1E4;ig_d=ig_v.prototype;
ig_d.O=function(a){if(this.jb){var b=window,c=a.lastIndexOf(".");if(c>=0){b=ig_e(a.substring(0,c));a=a.substring(c+1)}if(b[a]&&!b[a].zc)ig_a(new Error(a+" is already defined."));b[a]=this.Ld(a)}};ig_d.ta=function(a){if(this.jb){var b=window,c=a.lastIndexOf(".");if(c>=0){b=ig_e(a.substring(0,c));a=a.substring(c+1)}b[a]=function(){}}};ig_d.Ld=function(a){var b=this;function c(){for(var d=[],e=0;e<arguments.length;e++)d.push(arguments[e]);b.A.push([a,this,d])}c.zc=ig_b;return c};
ig_d.Qb=function(){if(this.A.length!=0){var a=this.A.shift(),b=a[0],c=a[1];a=a[2];try{var d=b instanceof Function?b:window[b];d.apply(c,a)}catch(e){}if(this.A.length>0){var f=this;setTimeout(function(){f.Qb()},0)}else{this.cc=ig_b;this.hf()}}};
ig_d.Hd=function(){for(var a=[],b=0;b<this.A.length;b++){var c=this.A[b][0];if(!(c instanceof Function))if(window[c].zc){a.push(c);this.A.splice(b,1);b--}}var d=this;setTimeout(function(){d.Qb()},0);if(a.length>0)ig_a(new Error("The following functions were not found in the post load file: "+a.join(", ")))};ig_d.hf=function(){for(var a=_gelstn("*"),b=0;b<a.length;b++){var c=a[b];c.className&&c.className.split&&ig_f(c,"disabled",ig_)}};
ig_d.Me=function(a,b){b=this.Le(b);_IG_AddEventHandler(a,b);setTimeout(b,ig_v.jd)};ig_d.Le=function(a){var b=this;return function(){if(!b.Mc){_IG_LoadScriptXDomain(a,"window._IG_DD_position",function(){b.Hd()});b.Mc=ig_b}}};ig_d.Dd=function(a){this.cc||!this.jb?a():this.A.push([a,ig_,[]])};var ig_w;ig_w||(ig_w=new ig_v(window.FLAG_isInSplitJS));function _IG_callPostLoad(a){ig_w.Dd(a)}function _IG_deferFunction(a){ig_w.O(a)}function _IG_ignoreFunction(a){ig_w.ta(a)}
function _IG_loadPostloadJS(a,b){ig_w.Me(a,b)};function _edit(a,b){function c(){b&&b();_sendx("/ig/ui?action=editsettings&m="+a);ig_j("edit","m_"+a)}var d=ig_Ea[a];if(d){d();c()}else _IG_LL_load("m_"+a+"_editbox",{mid:a},function(){_showUserPrefs(a,ig_c);c()});return ig_c}var ig_Ea={};function _IG_AddCustomEditHandler(a,b){ig_Ea[a]=b}function _cedit(a){_closeUserPrefs(a);var b=_gel("m_"+a+"_form");if(b){b.reset();_sendx("/ig/ui?action=canceledit&m="+a);ig_j("canceledit","m_"+a);return ig_c}}
function _uhc(a,b,c){b="m_"+a+"_"+b;var d=_gel(b);if(!d){d=document.createElement("INPUT");d.type="hidden";d.disabled=ig_b;d.name=b;_gel("m_"+a+"_form").appendChild(d)}d.value=c;d.disabled=ig_c}function _confirmDel(a,b,c,d){var e=_bidi_unicode_wrap(_get_module_title(a),_get_module_title_dir(a));d=d.replace(/MODULE_TITLE/,e);confirm(d)&&_del(a,b,c)}
function _get_module_title(a){if(typeof a=="object")a=a.id.replace("m_","");else if(typeof a=="string")a=a.replace("m_","");if(typeof _IG_MD!="undefined")return _IG_MD.m[a].ti;else return(a=_gel("m_"+a+"_title"))?_striptags(a.innerHTML):""}function _get_module_title_dir(a){if(typeof a=="object")a=a.id.replace("m_","");else if(typeof a=="string")a=a.replace("m_","");if(typeof _IG_MD!="undefined")return _IG_MD.m[a].ti_dir}
function _get_all_modules(){var a,b=_gelsbyregex("DIV",/^c_[0-9]+$/);a=[];for(var c=0;c<b.length;c++)b[c].style.display!="none"&&a.push(b[c]);a=a;b=[];c=/^m_[0-9]+$/;for(var d=0;d<a.length;d++){b[d]=[];for(var e=b[d],f=0;f<a[d].childNodes.length;f++){var h=a[d].childNodes[f];h.tagName=="DIV"&&h.style.display!="none"&&h.id&&c.test(h.id)&&e.push(h)}}if(window.gadgets&&window.gadgets.views&&window.gadgets.views.ViewManager&&window.gadgets.views.ViewManager.getCurrentMaxId)(a=window.gadgets.views.ViewManager.getCurrentMaxId())&&
b.length>0&&a&&b[0].unshift(_gel("m_"+a));return b}var ig_x=ig_c;function _del_is_done(){return _xsetp_is_done()&&ig_x}
function _del(a,b,c){ig_x=ig_c;_xsetp("m_"+a+"_enab=0&m_"+a+"_t="+b);if(b=_gel("undel_msg")){_gel("undel_title").innerHTML="&quot;"+_bidi_span_wrap(_get_module_title(a),_get_module_title_dir(a))+"&quot; ";b.style.display="block";ig_l("undo_msg","none");ig_l("undo_restore_msg","none")}ig_l("m_"+a,"none");ig_n=a;ig_o=c;ig_l(c,"");_mod=ig_b;ig_j("delete","m_"+a);ig_x=ig_b;return ig_c}
function _undel(){if(ig_n!=ig_){var a="m_"+ig_n,b=_gel(a);if(b){ig_l(a,"block");_xsetp("undel")}ig_l("undel_msg","none");ig_o!=ig_&&ig_l(ig_o,"none");ig_o=ig_n=ig_;ig_j("undelete",a)}}function _isModuleZipped(a){if(a=_gel("m_"+a+"_b"))return a.style.display=="none";return ig_c}
function _zm(a,b,c){var d=_gel("m_"+a+"_b");if(d){var e=!_isModuleZipped(a);d.style.display=e?"none":"block";if(d=_gel("m_"+a+"_zippy"))d.className=e?d.className.replace(/minbox/,"maxbox"):d.className.replace(/maxbox/,"minbox");c=c?"mmz":"mz";_xsetp(c+"="+a+":"+(e?"1":"0")+"&t="+b);ig_j(e?"zip":"unzip",a)}return ig_c}var _uli,_pnlo,_mpnlo,_pl,_mod,_cbp=ig_c,ig_Fa=ig_c,_table=ig_,_tabs=ig_;
function _upc(){var a=[];_cbp||(a[a.length]=["medit","display",_uli?"":"none"]);a[a.length]=["panelo","display",_pnlo?"":"none"];a[a.length]=["panelc","display",_pnlo?"none":""];if(_mod){a[a.length]=["unmod","display","none"];a[a.length]=["mod","display",""]}else{a[a.length]=["mod","display","none"];a[a.length]=["unmod","display",""]}a=a;for(var b=_gelstn("*"),c=0,d;d=b[c];c++)for(var e=0;e<a.length;e++)if(d.className==a[e][0])d.style[a[e][1]]=a[e][2];_IG_callPostLoad(_init_drag_drop)}
function _init_drag_drop(){if(_pl)if(_cbp||_uli)if(!ig_Fa&&!_mpnlo){_IG_TriggerCustomEvent("initdrag",_table,_tabs);ig_Fa=ig_b}}var ig_y=0;
function _tp(a){ig_y>0&&clearInterval(ig_y);_pnlo=a;_mod=ig_b;_xsetp("pnlo="+(a?1:0));_upc();var b=_gel("cpnl"),c=_gel("cpnlc"),d=b.offsetWidth,e,f;if(a){e=c.offsetWidth;f="visible";ig_l("ehdr","");ig_l("nhdr","none")}else{e=1;f="hidden";ig_l("ehdr","none");ig_l("nhdr","")}b.style.overflow="hidden";a=100;var h=10,g=0;ig_y=setInterval(function(){var k=g/h,j=d+(e-d)*k;b.style.width=j+"px";g++;if(k>=1){clearInterval(ig_y);ig_y=0;b.style.width=e+"px";b.style.overflow=f}},a/h);return ig_c}
function _ts(a,b){a=_gel(a+b);if(a.className=="mlist_open"){a.className="mlist_closed";a="pnlsc"}else{a.className="mlist_open";a="pnlso"}_xsetp(a+"="+_esc(b));return ig_c}function _add_m(a,b){_dlsetp(a,b)}function _add_m_confirm(a,b,c){confirm(b)&&_add_m(a,c)}function _add_f(a){_add_m("n_25="+_esc("url="+_esc(a)))}var ig_Ga=/^_add_m(_confirm)?\(\"[^"]+\"(, *\"[^"]+\")?\)$/,ig_z=ig_b;function _find_feed_is_done(){return ig_z}
function _find_feed(a){ig_z=ig_c;var b="acd";if(!a){var c=_gelstn("div");if(c)for(var d=0,e;e=c[d];d++)e.id&&e.id.indexOf("ps")==0&&e.className=="mlist_open"&&_ts("ps",e.id.substring(2));if(_gel("add_custom"))a=_gel("add_custom").value}if(!a||a==""){b="advdsrch";a=_gel("add_advd").value}ig_l("ffresults","none");ig_l("ffloading","block");_sendx("/ig/feeds"+_qs()+"q="+_esc(a)+"&page="+_esc(b),ig_Ha);return ig_c}
function ig_Ha(a){ig_l("ffloading","none");ig_l("ffresults","block");if(a.length>0&&a.charAt(0)=="<"){if(_gel("ffresults"))_gel("ffresults").innerHTML=a}else{a.match(ig_Ga)!=ig_;eval(a)}ig_z=ig_b}function _add_remote_module(a,b,c){_sendx("/ig/feeds"+_qs()+"module=1&q="+_esc(a),function(d){b();d=d;var e=c,f=/_add_m_confirm\((\"[^"]+\"),\s*(\"[^"]+\")(,\s*\"[^"]+\")?\)/,h=/^alert\(\"[^"]+\"\)$/;if(d.match(ig_Ga)!=ig_||d.match(h)!=ig_){if(e)d=d.replace(f,"_add_m($1$3)");eval(d)}});return ig_c}
function _ListApp(a,b,c){this.items=a;this.na=[];this.Dc=b;this.ba=c;this.Ra="m_"+c+"_App";this.fc=_gel("m_"+c+"_disp");this.Jf=ig_b;this.U=_gel("m_"+c+"_val");this.H=_gel("m_"+c+"_name");if(!this.H)this.H=this.U;if(this.H){this.$b=this.H.value;this.bc=this.U.value}this.Nc=[].concat(this.items)}ig_d=_ListApp.prototype;ig_d.reset=function(){this.items=[].concat(this.Nc);this.na=[];this.refresh()};ig_d.sort=function(a,b){return a.Ua(b)};
ig_d.df=function(){var a="";if(_old_html)a="<table cellspacing=0 cellpadding=0 border=0>";for(var b="",c=this.items,d=0;d<c.length;d++)if(c[d]){a+=_old_html?"<tr><td nowrap><font size=-1>"+c[d].gb()+'</font></td><td><a href="#" onclick="'+this.Ra+"._del("+d+');return false"><img src="/ig/images/x.gif" width=16 height=13 border=0></a></td></tr>':'<a href="#" onclick="'+this.Ra+"._del("+d+');return false" class="delbox listdelbox"></a>'+c[d].gb()+'<div class="c"></div>';if(parseInt(c[d].Pa,10)<0)b+=
c[d].Ha(d)}else{this.items.splice(d,1);d--}c=this.na;var e="";for(d=0;d<c.length;d++)if(parseInt(c[d].Pa,10)>=0)e+=","+c[d].Pa;a+=this.nc(b,e);return a};ig_d.nc=function(a,b){var c="<input type=hidden name=m_"+this.ba+'_del value="'+b+'"><input type=hidden name=m_'+this.ba+'_add value="'+a+'">';if(_old_html)c="</table><input type=hidden name=m_"+this.ba+'_del value="'+b+'"><input type=hidden name=m_'+this.ba+'_add value="'+a+'">';return c};
ig_d.refresh=function(){this.Jf&&this.items.sort(this.sort);this.fc.innerHTML="<font size=-1>"+this.df()+"</font>"};ig_d.add=function(a,b){a||(a=_trim(this.H.value));b||(b=_trim(this.U.value));a=new this.Dc(a,b,-1);if(a.mb()){this.items[this.items.length]=a;this.refresh();this.H.value=this.$b;this.U.value=this.bc}};ig_d._del=function(a){this.na[this.na.length]=this.items[a];this.items.splice(a,1);this.refresh()};
function _PrefListApp(a,b,c,d,e){var f=typeof c=="string"?[]:c;d=new _ListApp(f,d,e);for(var h in d)this[h]=d[h];typeof c=="string"&&this.$e(c);this.cf=a;this.lg=b;this.Ra="m_"+e+"_"+a+"_App";this.fc=_gel("m_"+e+"_"+a+"_disp");this.H=this.U=_gel("m_"+e+"_"+a+"_val");this.bc=this.$b="";this.nc=_PrefListApp_get_tail}function _PrefListApp_get_tail(){var a="</table>";_gel("m_"+this.ba+"_"+this.cf).value=this.Kf();return a}
_PrefListApp.prototype.$e=function(a){if(a.length!=0){a=_IG_Prefs.Nb(a);for(var b=[],c=0;c<a.length;c++){var d=new this.Dc(a[c],a[c],-1);b[b.length]=d}this.items=b;this.Nc=[].concat(b)}};_PrefListApp.prototype.Kf=function(){for(var a=[],b=0;b<this.items.length;b++)a[a.length]=this.items[b].F;return _IG_Prefs.Lb(a)};function _ListItem(a,b,c){this.p=a;this.F=b;this.Pa=c}_ListItem.prototype.mb=function(){return this.p!=""};_ListItem.prototype.Ua=function(){return 0};_ListItem.prototype.gb=function(){return _hesc(this.p)};
_ListItem.prototype.Ha=function(){return"&"+_esc(this.p)+"="+_esc(this.F)};function _BMListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_k(_ListItem,_BMListItem);ig_d=_BMListItem.prototype;ig_d.mb=function(){return _ListItem.prototype.mb.call(this)&&this.p!="http://"};ig_d.eb=function(){if(this.F)return this.F;else{var a=this.p;if(a.indexOf("http://")==0)a=a.substring(7);if(a.indexOf("www.")==0)a=a.substring(4);return a}};
ig_d.gb=function(){return'<a href="'+this.p+'" target=bmwindow>'+_hesc(this.eb())+"</a>"};ig_d.Ha=function(a){return"&b"+a+"="+_esc(this.p)+"&t"+a+"="+_esc(this.F)};ig_d.Ua=function(a){var b=_uc(this.eb());a=_uc(a.eb());if(b==a)return 0;return b<a?-1:1};function _WthrListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_k(_ListItem,_WthrListItem);_WthrListItem.prototype.Ha=function(){var a="&"+_esc(this.p);if(this.F)a+="="+_esc(this.F);return a};
function _FListItem(a,b,c,d){_ListItem.call(this,a,b,c);this.ja=d||0}ig_k(_ListItem,_FListItem);_FListItem.prototype.Ha=function(){return"&"+_esc(this.p)};_FListItem.prototype.Ua=function(a){var b=this;if(b.ja<a.ja)return-1;if(b.ja>a.ja)return 1;b=_uc(b.p);a=_uc(a.p);if(b<a)return-1;if(b>a)return 1;return 0};function ig_A(a){if(!a)a=document.body;return a.scrollHeight>a.offsetHeight?a.scrollHeight:a.offsetHeight}
function ig_B(){return self.pageYOffset?self.pageYOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop}function _closePromoBox(a){_toggle(_gel("promo"+a));_xsetp("gpc="+a+":-1")}_exportSymbols("",["pageHeight",ig_A,"scrollTop",ig_B]);var ig_C={},ig_Ia={};function _place(a,b){var c=ig_Ia[a];if(c)c(b);else{ig_C[a]||(ig_C[a]=[]);ig_C[a].push(b)}}
function _register_place(a,b){ig_Ia[a]=b;var c=ig_C[a];if(c){for(var d=0;d<c.length;d++)b(c[d]);ig_C[a]=ig_}}function _enableGS(a,b){a.action="https://www.google.com/accounts/CheckCookie";a.method="get";ig_p(a,"service",b);ig_p(a,"continue",document.location);ig_p(a,"skipvpage",ig_b);return ig_b};function _reload(a,b){var c=a-(new Date).getTime();if(c>1E3)setTimeout("_reload("+a+")",c);else if(b)document.location.replace(ig_Ja(document.location.href,document.location.pathname));else{document.cookie="IGREL=1";document.location.replace(document.location.href.split("#")[0])}}var ig_Ka=/^([^?#]+)(?:\?([^#]*))?(#.*)?/;function ig_Ja(a,b){var c=ig_Ka.exec(a),d=c[1];if(b=="/")d+="ig";d+="?";if(b=c[2])d+=b;if(!_argsUrl(a).refresh){if(b)d+="&";d+="refresh=1"}return d}
var ig_D={db:0,$c:1800,pb:ig_,ob:ig_,Qa:ig_b,Z:ig_,gd:ig_,Rb:600,ga:function(){ig_D.db=(new Date).getTime()+ig_D.$c*1E3},Ze:function(){if((new Date).getTime()>ig_D.db)window.gTalkNotifier&&window.gTalkNotifier._isAnyMoleOpen&&window.gTalkNotifier._isAnyMoleOpen()?ig_D.ga():_testConnection(function(){_reload(ig_D.db,ig_D.gd)},ig_D.ga)},rb:function(a){ig_D.ga();ig_D.pb&&ig_D.pb(a)},qb:function(a){ig_D.ga();ig_D.ob&&ig_D.ob(a)}};
function _IG_disable_refresh_cycle(){ig_D.Qa=ig_c;_IG_suspend_refresh_cycle()}function _IG_suspend_refresh_cycle(){if(ig_D.Z!=ig_){clearInterval(ig_D.Z);ig_D.Z=ig_}}function _IG_restart_refresh_cycle(){!ig_D.Qa||ig_D.Z!=ig_||ig_La()}
function _IG_start_refresh_cycle(a,b,c){if(ig_D.Qa){ig_D.pb=document.onmousedown;ig_D.ob=document.onkeyup;ig_D.$c=a;ig_D.Rb=b;if(c)ig_D.gd=c;if(document.addEventListener){document.addEventListener("keyup",ig_D.qb,ig_c);document.addEventListener("mousedown",ig_D.rb,ig_c)}else if(document.attachEvent){document.attachEvent("onkeyup",ig_D.qb);document.attachEvent("onmousedown",ig_D.rb)}else{document.onkeyup=ig_D.qb;document.onmousedown=ig_D.rb}ig_La()}}
function ig_La(){ig_D.ga();ig_D.Z=setInterval(ig_D.Ze,ig_D.Rb*1E3)}function _testConnection(a,b,c){var d=ig_m(),e="/ig/nop?t="+(new Date).getTime();c||(c=3500);d.open("GET",e,ig_b);d.onreadystatechange=function(){if(d.readyState==4&&a)if(200<=d.status&&d.status<300||d.status==1223){b=ig_;a()}};try{d.send(ig_)}catch(f){}function h(){if(b){a=ig_;b()}}setTimeout(h,c)};function _IG_GetCachedUrl(a,b){b=typeof b=="object"?b:{};var c=window.location.href,d="/ig/proxy?",e=/^http:\/\/[^\/]+\/ig\/ifr[?]/;if((e=e.exec(c))||c.indexOf("http://www.google.cn/ig/china")==0){if(window.location.host!="p.gmodules.com"&&_et)d+="et="+_esc(_et)+"&"}else d="http://p.gmodules.com/ig/proxy?";if(!isNaN(b.refreshInterval)&&b.refreshInterval>=0)d=_appendMaxAgeParameter(d,b.refreshInterval);return d+"url="+_esc(a)+"&log=1"}function _IG_GetImageUrl(a,b){return _IG_GetCachedUrl(a,b)}
function _IG_GetImage(a,b){var c=document.createElement("img");c.src=_IG_GetCachedUrl(a,b);return c};function _IG_Callback(a){var b=arguments;return function(){for(var c=[],d=0;d<arguments.length;d++)c[c.length]=arguments[d];for(d=1;d<b.length;d++)c[c.length]=b[d];a.apply(ig_,c)}};var _IG_Layouts={};_IG_Layouts._selectLayout=function(a){for(var b=_gel("edit_this_tab_form").edit_this_tab_selected_layout,c=0;c<b.length;c++){var d=b[c].value,e=_gel("edit_this_tab_layoutimg_"+d);if(d!=a){b[c].checked=ig_c;if(e.src.indexOf("_highlight")!=-1)e.src=e.src.substring(0,e.src.indexOf("_highlight"))+".gif"}else{b[c].checked=ig_b;if(e.src.indexOf("_highlight")==-1)e.src=e.src.substring(0,e.src.indexOf(".gif"))+"_highlight.gif"}}};var ig_E=function(){var a=ig_c,b=[],c=ig_,d=ig_;return{init:function(){},load:function(e,f,h){if(_gel(e))h(f);else{b.push({id:e,args:f,callback:h});if(!a)if(c){d(c,b);b=[]}else{_sendx("/ig/ui?action=lazy&id="+e,ig_,ig_c,ig_);if(!(c||a)){a=ig_b;_IG_LoadScript("/ig/ll"+window.location.search,"")}}}},Ne:function(e,f){c=e;d=f;a=ig_c;d(c,b);b=[]},pg:function(){a=ig_c;b=[];d=c=ig_}}}(),_IG_LL_init=ig_E.init,_IG_LL_load=ig_E.load,_IG_LL_loaded=ig_E.Ne;var ig_F=[];function _IG_isModuleInVisibleArea(a){var b=ig_B(),c,d=c=0;if(window.innerHeight){c=window.innerWidth;d=window.innerHeight}else if(document.documentElement&&document.documentElement.clientHeight){c=document.documentElement.clientWidth;d=document.documentElement.clientHeight}else if(document.body.clientHeight){c=document.body.clientWidth;d=document.body.clientHeight}c={width:c,height:d};c=c.height;d=parseInt(a.style.height,10);a=_findPos(a)[1];return a+d>b&&a<b+c}
function _IG_delayLoadGadget(a){ig_F.push(a)}function _IG_loadDelayLoadGadgets(){for(var a=0;a<ig_F.length;++a){var b=_gel("remote_iframe_"+ig_F[a].id);if(b){var c=b.getAttribute("src");if(c==ig_||c=="")b.src=ig_F[a].base_iframe_url}}};function _IG_MD_Generate(a){var b={t:{},dt:[],m:{},f:{}},c=a,d=b;if(c.t)for(var e=0;e<c.t.length;++e){var f=c.t[e];d.t[f.i]=f;d.t[f.i].m={}}c=a;d=b;if(c.f)for(e=0;e<c.f.length;++e){f=c.f[e];d.f[f.n]=f}c=a;d=b;if(c.m)for(e=0;e<c.m.length;++e){f=c.m[e];f.fa||(f.fa={});d.m[f.i]=f;var h=d.t[f.t];if(h)h.m[f.i]=f}if(a.ct!=ig_&&b.t)b.ct=b.t[a.ct];a=a;c=b;if(a.dt)for(d=0;d<a.dt.length;++d)c.dt[d]=c.t[a.dt[d]];return b};var ig_G;
ig_G||(ig_G=function(){function a(j){return j<10?"0"+j:j}function b(j){e.lastIndex=0;return e.test(j)?'"'+j.replace(e,function(l){var m=g[l];if(typeof m==="string")return m;return"\\u"+("0000"+(+l.charCodeAt(0)).toString(16)).slice(-4)})+'"':'"'+j+'"'}function c(j,l){var m,n,i=f,o,p=l[j];if(p&&typeof p==="object"&&typeof p.toJSON==="function")p=p.toJSON(j);if(typeof k==="function")p=k.call(l,j,p);switch(typeof p){case "string":return b(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";f+=h;o=[];if(typeof p.length==="number"&&!p.propertyIsEnumerable("length")){n=p.length;for(j=0;j<n;j+=1)o[j]=c(j,p)||"null";l=o.length===0?"[]":f?"[\n"+f+o.join(",\n"+f)+"\n"+i+"]":"["+o.join(",")+"]";f=i;return l}if(k&&typeof k==="object"){n=k.length;for(j=0;j<n;j+=1){m=k[j];if(typeof m==="string")if(l=c(m,p))o.push(b(m)+(f?": ":":")+l)}}else for(m in p)if(Object.hasOwnProperty.call(p,m))if(l=c(m,p))o.push(b(m)+(f?": ":":")+l);l=o.length===0?"{}":f?"{\n"+f+o.join(",\n"+
f)+"\n"+i+"}":"{"+o.join(",")+"}";f=i;return l}}Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z"};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,h,g={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;return{stringify:function(j,l,m){l=l;m=m;var n;h=f="";if(typeof m==="number")for(n=0;n<m;n+=1)h+=" ";else if(typeof m==="string")h=m;if((k=l)&&typeof l!=="function"&&(typeof l!=="object"||typeof l.length!=="number"))ig_a(new Error("JSON.stringify"));return c("",{"":j})},parse:function(j,l){function m(i,o){var p,r,q=i[o];if(q&&typeof q==="object")for(p in q)if(Object.hasOwnProperty.call(q,p)){r=m(q,p);if(r!==
undefined)q[p]=r;else delete q[p]}return n.call(i,o,q)}var n=l;d.lastIndex=0;if(d.test(j))j=j.replace(d,function(i){return"\\u"+("0000"+(+i.charCodeAt(0)).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(j.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+j+")");return typeof n==="function"?m({"":j},""):j}ig_a(new Error("JSON.parse"))}}}());
ig_G.parse=function(){var a=ig_G.parse;return function(b,c){try{return a(b,c)}catch(d){return ig_c}}}();function ig_Oa(a){var b=document.createElement("DIV");b.innerHTML="<iframe onload='this.pool_locked=false'></iframe>";var c=b.getElementsByTagName("IFRAME")[0];c.style.visibility="hidden";c.style.width=c.style.height="0px";c.style.border="0px";c.style.position="absolute";c.Lc=a;this.l[this.l.length]=c;b.removeChild(c);return c}
function ig_Pa(a){if(a.match(/^http[s]?:\/\//)){var b=this;window.setTimeout(function(){for(var c=ig_,d=b.l.length-1;d>=0;d--){var e=b.l[d];if(e&&!e.Lc){e.parentNode.removeChild(e);if(window.ActiveXObject){b.l[d]=ig_;b.l.splice(d,1)}else{e.Lc=ig_b;c=e;break}}}c=c?c:b.Md(ig_b);c.src=a;document.body.appendChild(c)},0)}}function ig_Qa(){for(var a=0;a<this.l.length;a++){this.l[a].onload=ig_;this.l[a]=ig_}this.l.length=0;this.l=[]}
function ig_Ra(){for(var a=0;a<this.l.length;a++){var b=this.l[a];b&&b.parentNode.removeChild(b)}}function ig_Sa(){this.l=[];this.Md=ig_Oa;this.vc=ig_Pa;this.clear=ig_Qa;this.gc=ig_Ra}function ig_Ta(a,b){_IFPC.ea[a]=b}function ig_Ua(a){delete _IFPC.ea[a]}
function ig_Va(a,b,c,d,e,f,h,g){if(!_IFPC.ab){var k=4095-d.length;k=parseInt(k/3,10);if(typeof h=="undefined")h=ig_b;if(g){h={s:b,a:c,f:"..",t:window._isk[a.split("_")[2]]};a=[a,"..",_IFPC.Ta,1,1,encodeURIComponent(ig_G.stringify(h))].join("&");_IFPC.sa.vc(d+"#"+a)}else{c=c.slice(0);c.unshift(_IFPC.ef(e));c.unshift(f);c.unshift(b);c.unshift(a);b=_IFPC.hc(c);c=parseInt(b.length/k,10);if(b.length%k>0)c+=1;for(e=0;e<c;e++){f=b.substr(e*k,k);f=[a,_IFPC.Ta,c,e,f,h];_IFPC.sa.vc(d+"#"+_IFPC.hc(f))}}_IFPC.Ta++}}
function ig_Wa(){_IFPC.ea={};_IFPC.L={};_IFPC.sa.clear()}function ig_Xa(){if(!_IFPC.ab){_IFPC.ab=ig_b;_IFPC.sa.gc();_IFPC.clear()}}
function ig_Ya(a){var b=_IFPC.Za(a)[0],c=ig_;try{c=window.parent.frames[b]}catch(d){}try{if(!c&&window.parent.parent.frames[b]!=window.parent){window.parent.parent.frames[b].setTimeout(function(){},0);c=window.parent.parent.frames[b]}}catch(e){}if(!c)c=window.parent.parent;if(!c||c._IFPC==undefined)c=ig_;else{b=function(){c._IFPC.handleRequest(a)};window.ActiveXObject?b():c.setTimeout(b,0)}}
function ig_Za(a){a=_IFPC.Za(a);var b=a.shift(),c=a.shift(),d=a.shift(),e=a.shift(),f=a.shift();a=a.shift();b=b+"_"+c;_IFPC.I[b]||(_IFPC.I[b]=[]);_IFPC.I[b].push([e,f]);if(_IFPC.I[b].length==d){_IFPC.I[b].sort(function(g,k){return parseInt(g[0],10)-parseInt(k[0],10)});f="";for(e=0;e<d;e++)f+=_IFPC.I[b][e][1];_IFPC.I[b]=ig_;e=_IFPC.Za(f);b=e.shift();c=e.shift();d=e.shift();f=e.shift();var h=_IFPC.ne(c);if(h){a=h.apply(ig_,e);if(_IFPC.Ee(f)){a.unshift(f);_IFPC.call(b,_IFPC.Bb,a,d,ig_,"")}}else if(a)ig_a(new Error("Service "+
c+" not registered."))}}function ig__a(a){return _IFPC.ea.hasOwnProperty(a)?_IFPC.ea[a]:ig_}function ig_0a(a){var b="";if(a&&typeof a=="function"){b=_IFPC.ke();_IFPC.L[b]=a}return b}function ig_1a(a){if(_IFPC.L.hasOwnProperty(a))_IFPC.L[a]=ig_}function ig_2a(a){if(a&&_IFPC.L.hasOwnProperty(a))return _IFPC.L[a];return ig_}function ig_3a(){return _IFPC.Ab+_IFPC.Ed++}function ig_4a(a){return(a+"").indexOf(_IFPC.Ab)==0}
function ig_5a(a){a=a.split("&");for(var b=0;b<a.length;b++){var c=decodeURIComponent(a[b]);try{c=ig_G.parse(c)}catch(d){}a[b]=c}return a}function ig_6a(a){for(var b=[],c=0;c<a.length;c++){var d=ig_G.stringify(a[c]);b.push(encodeURIComponent(d))}return b.join("&")}function ig_7a(a){var b=_IFPC.de(a);if(b){for(var c=[],d=1;d<arguments.length;d++)c[c.length]=arguments[d];b.apply(ig_,c);_IFPC.Wf(a)}else ig_a(new Error("Invalid callbackId"))}var _IFPC={};
function ig_8a(a){if((a=window._argsUrl&&window._argsUrl(a))&&a.exp_rpc_js==1)window.FLAG_use_rpc_js=ig_b;if(window.FLAG_use_rpc_js){}else{_IFPC={registerService:ig_Ta,unregisterService:ig_Ua,call:ig_Va,clear:ig_Wa,gc:ig_Xa,og:ig_Ya,mg:ig_Ya,handleRequest:ig_Za,Ab:"cbid",Bb:"ifpc_callback",sa:new ig_Sa,I:{},ea:{},L:{},Ed:0,Ta:0,ab:ig_c,ne:ig__a,ef:ig_0a,Wf:ig_1a,de:ig_2a,ke:ig_3a,Ee:ig_4a,Za:ig_5a,hc:ig_6a,Fd:ig_7a};_IFPC.registerService(_IFPC.Bb,_IFPC.Fd);}}
ig_8a(document.location.href);function _IG_Prefs_PrefsData(){}_IG_Prefs_PrefsData.prototype.value=ig_;
function _IG_Prefs(a){a=a;if(typeof remote_modules!=="object"){a=(a=_args().mid)?a:0;_IG_Prefs._parseURL(a);_IG_Prefs.va[a]=ig_c}else{if(!a)ig_a(new Error("Module ID is required as first argument to _IG_Prefs() for inlined modules"));_IG_Prefs.va[a]=ig_b}_IG_Prefs.g[_IG_Prefs.D+a]||(_IG_Prefs.g[_IG_Prefs.D+a]={});this.g=_IG_Prefs.g[_IG_Prefs.D+a];this.d=a;this.kg=/(.*)(\<ph.*?\>\s*(\<ex\>(.*?)\<\/ex\>)?\s*%1\s*\<\/ph\>)(.*)/}ig_d=_IG_Prefs.prototype;
ig_d.Y=function(a,b){if(b==undefined)b=ig_;a=this.g[a];if(a==undefined)return b;a=a.value;return a!=undefined?a:b};ig_d.fb=function(a,b){return this.Y(_IG_Prefs.k+a,b)};ig_d.getString=function(a){var b="";a=this.fb(a,b);return a!=ig_?a+"":b};ig_d.ge=function(a){var b=0;a=parseInt(this.fb(a,b),10);return isNaN(a)?b:a};ig_d.getBool=function(a){a=this.getString(a);return a==="true"||!!parseInt(a,10)};ig_d.ce=function(a){return _IG_Prefs.Nb(this.fb(a,""))};ig_d.tf=function(a,b){this.set(a,_IG_Prefs.Lb(b))};
ig_d.ee=function(){return this.getString(".country")};ig_d.he=function(){return this.getString(".lang")};ig_d.ie=function(a){return this.Y(_IG_Prefs.Fb+a,"")+""};ig_d.set=function(){var a=Math.floor(arguments.length/2);if(a!=0){for(var b=[],c=0;c<a;++c){var d=arguments[c*2],e=_IG_Prefs.k+d,f=arguments[c*2+1]+"";this.Zf(e,f)&&b.push(d,f)}if(b.length!=0)_IG_Prefs.va[this.d]?_IG_Prefs._setP(this.d,b):_IFPC_SetPref(b)}};
function ig_9a(a){var b="todos",c=_ig_gmid_(a);b=(new _IG_Prefs(Number(c))).getString(b);if(navigator.userAgent.indexOf("MSIE")!=-1&&b.length>1E3){c=Math.ceil(b.length/1E3);for(var d=0;d<c;d++){var e=b.substr(d*1E3,1E3);ig_$a(a,e,d,c)}}else ig_$a(a,b)}function ig_$a(a,b,c,d){var e=_ig_gmid_(a);b=[b];d&&b.push(c,d);_IFPC.call(a,"populate_todos_pref",b,window._ifpc_relay_url[e],ig_,"http://"+window.location.host+"/ig/images/rpc_relay.html",ig_b,ig_b)}
window._IG_CONTAINER&&_IFPC.registerService("get_todos_pref_for_migration",ig_9a);_IG_Prefs.prototype.le=function(){var a=["__module_id__="+this.d];for(var b in this.g)a.push(encodeURIComponent(b)+"="+encodeURIComponent(this.g[b].value));return a.join("&")};_IG_Prefs.prototype.dump=function(){document.write("<pre>");for(var a in this.g)document.writeln(a+" = "+this.Y(a,ig_));document.write("</pre>")};
_IG_Prefs.prototype.Zf=function(a,b){var c=this.g[a];if(c&&c.value===b)return ig_c;if(c)c.value=b;else{c=new _IG_Prefs_PrefsData;c.value=b;this.g[a]=c}return ig_b};_IG_Prefs.va={};_IG_Prefs.g={};_IG_Prefs.D="m_";_IG_Prefs.k="up_";_IG_Prefs.md="up_";_IG_Prefs.Fb="msg_";_IG_Prefs.Ka={};_IG_Prefs.Ka[_IG_Prefs.md]="value";_IG_Prefs.eg=function(a,b){if(a.indexOf)return a.indexOf(b);else{for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1}};
_IG_Prefs._parseURL=function(a){_IG_Prefs.va[a]=ig_c;for(var b={},c=ig_g(),d=0;d<c.length;++d){var e=c[d].indexOf("=");if(e>=0){var f=c[d].substring(0,e);f=f.replace(/\+/g," ");e=c[d].substring(e+1);e=e.replace(/\+/g," ");e=_unesc(e);var h=ig_c;for(var g in _IG_Prefs.Ka)if(f.indexOf(g)===0){h=ig_b;f=f.substring(g.length);f=_IG_Prefs.k+f;b[f]=b[f]?b[f]:new _IG_Prefs_PrefsData;if(g===_IG_Prefs.dg||g===_IG_Prefs.cg)e=e=="true";b[f][_IG_Prefs.Ka[g]]=e;break}if(!h)if(f.indexOf(_IG_Prefs.Fb)===0)_IG_Prefs.K(a,
f,e);else if(f===".lang"||f===".country")_IG_Prefs.K(a,_IG_Prefs.k+f,e)}}if(window.IDIModule){b=window.IDIModule.getPrefs();for(d in b)_IG_Prefs.K(a,d,b[d])}else for(f in b)_IG_Prefs.K(a,f,b[f].value)};_IG_Prefs.K=function(a,b,c){a=_IG_Prefs.D+a;if(typeof _IG_Prefs.g[a]!=="object")_IG_Prefs.g[a]={};if(typeof _IG_Prefs.g[a][b]!=="object"){_IG_Prefs.g[a][b]=new _IG_Prefs_PrefsData;b=_IG_Prefs.g[a][b];b.value=c}};
_IG_Prefs.Bf=function(a,b,c){var d=_IG_Prefs.D+a;if(typeof _IG_Prefs.g[d]!=="object")_IG_Prefs.K(a,b,c);else if(typeof _IG_Prefs.g[d][b]!=="object")_IG_Prefs.g[d][b]=new _IG_Prefs_PrefsData;a=_IG_Prefs.g[d][b];a.value=c};_IG_Prefs._addAll=function(a,b){for(var c=0;c<b.length;++c)_IG_Prefs.K(a,b[c][0],b[c][1])};_IG_Prefs.Lb=function(a){var b=a.length&&a.join;if(b){b=[];for(var c=0;c<a.length;++c)b.push(a[c].replace(/\|/g,"%7C"));return b.join("|")}else return a};
_IG_Prefs.Nb=function(a){a=a.length>0?a.split("|"):[];for(var b=0;b<a.length;++b)a[b]=a[b].replace(/%7C/g,"|");return a};
_IG_Prefs.W=function(a,b){a=_IG_Prefs.D+a;a=_IG_Prefs.g[a];if(a==ig_)return b;b=b.split("#");var c=b[0].split("?"),d=c;if(b.length>1&&("&"+b[1]).indexOf("&"+_IG_Prefs.k)!==-1&&(c.length===1||("&"+c[1]).indexOf("&"+_IG_Prefs.k)===-1))d=b;var e=[];if(d.length>1&&d[1].length!==0)e=d[1].split("&");for(var f=0;f<e.length;++f)e[f].indexOf(_IG_Prefs.k)===0&&e.splice(f--,1);for(var h in a)h.indexOf(_IG_Prefs.k)!==0||h.indexOf(_IG_Prefs.k+".lang")===0||h.indexOf(_IG_Prefs.k+".country")===0||h.indexOf(_IG_Prefs.k+
"synd")===0||e.push(_esc(h)+"="+_esc(a[h].value));d[1]=e.join("&");b[0]=c.join("?");return b.join("#")};_IG_Prefs._setPrefs=function(a,b){for(var c=Math.floor(b.length/2),d=0;d<c;++d){var e=_IG_Prefs.k+b[d*2],f=b[d*2+1];_IG_Prefs.Bf(a,e,f)}};_IG_Prefs._setP=function(a,b){if(_args().synd!=="open"){for(var c=Math.floor(b.length/2),d=[],e=0;e<c;++e){var f=_IG_Prefs.k+b[e*2],h=b[e*2+1];d.push(_IG_Prefs.D+a+"_"+f+"="+_esc(h))}d.length!==0&&_xsetp(d.join("&"))}};
_exportClass("google.gadgets","Prefs",_IG_Prefs,["getString",_IG_Prefs.prototype.getString,"getInt",_IG_Prefs.prototype.ge,"getBool",_IG_Prefs.prototype.getBool,"getArray",_IG_Prefs.prototype.ce,"setArray",_IG_Prefs.prototype.tf,"getLang",_IG_Prefs.prototype.he,"getCountry",_IG_Prefs.prototype.ee,"getMsg",_IG_Prefs.prototype.ie,"getPreloadedString",_IG_Prefs.prototype.le,"set",_IG_Prefs.prototype.set,"dump",_IG_Prefs.prototype.dump]);function _IG_FR_getFeed(a){return window["FEED"+a]||{}}
function _IG_FR_toggle(a,b,c,d){c=c||"";d=d||"";var e=_gel("ft_"+a+"_"+b),f=_gel("fb_"+a+"_"+b),h=_gel("ftl_"+a+"_"+b);if(f.style.display=="block")ig_ab(e,f,h,c);else{var g=_IG_FR_getFeed(a);if(!g.has_entries&&!g.is_fetching){g.is_fetching=ig_b;_IG_FetchFeedAsJSON(g.url,_IG_Callback(ig_bb,a,b,c,d),g.num_items+15,ig_b)}else{for(var k=0;k<g.num_items;++k){var j=_gel("ftl_"+a+"_"+k);j&&ig_ab(_gel("ft_"+a+"_"+k),_gel("fb_"+a+"_"+k),j,c)}a=a;b=b;e=e;c=f;g=h;d=d;e.className=ig_H(e)?"fminbox_reverse_directionality":
"fminbox";e.title=d;if(_old_html||_use_old_feed_styles)e.className="fbox fminbox";c.style.display="block";c.style.maxHeight=c.offsetWidth*1.5+"px";g.className=ig_H(e)?"sftl_reverse_directionality":"sftl";window._IG_FRUC_setFeedAsRead&&window._IG_FRUC_setFeedAsRead(a,b);if(f.style.maxHeight&&parseInt(f.style.maxHeight,10)<ig_cb(h.offsetWidth,f))f.style.height=f.style.maxHeight}}}
function ig_bb(a,b,c,d,e){var f=_IG_FR_getFeed(b);f.is_fetching=ig_c;if(a&&a.Entry){for(var h=0;h<a.Entry.length;h++)if(a.Entry[h].ID!="no_id"){var g=_gel("fb_"+b+"_"+a.Entry[h].ID);if(g)g.innerHTML=a.Entry[h].Summary}f.has_entries=ig_b;_IG_FR_toggle(b,c,d,e)}}function ig_H(a){return a.className.match(/reverse_directionality$/)=="reverse_directionality"}
function ig_ab(a,b,c,d){a.className=ig_H(a)?"fmaxbox_reverse_directionality":"fmaxbox";a.title=d;if(_old_html||_use_old_feed_styles)a.className="fbox fmaxbox";b.style.display="none";b.style.maxHeight="";c.className=ig_H(a)?"uftl_reverse_directionality":"uftl"}function ig_cb(a,b){var c=document.createElement("div");c.style.left=-screen.width;c.style.top=-screen.height;c.style.width=a;c.innerHTML=b.innerHTML;document.body.appendChild(c);a=c.clientHeight;document.body.removeChild(c);return a}
function _IG_RegisterContainerScrollHandler(a){if(navigator.userAgent.indexOf("Firefox")>=0)window.addEventListener("scroll",a,ig_c);else window.onscroll=a}function _IG_GetContainerVisibleHeight(){return document.documentElement.clientHeight}function _IG_GetContainerTotalHeight(){return document.body.scrollHeight}function _IG_GetContainerScrollTop(){return document.documentElement.scrollTop}
function ig_db(a){var b=_gel("hl");b=b?b.value:"en";return"/reader/ig/feed/"+_esc(_IG_FR_getFeed(a).url)+"?hl="+b}function ig_eb(a,b){if(window._max_strategies){b=ig_db(a)+(b?"&i="+b:"");window._max_strategies[a]._updateIframeSrc(b)}}function _IG_FR_maxModule(a,b,c){ig_eb(a,b);window._IG_maximize_view(a,"feed",c)}
function _IG_FR_init(a){window._max_strategies&&_IG_callPostLoad(function(){window._max_strategies[a]=new window._IG_inlinedTransitionStrategy(a,ig_db(a),ig_,_IG_isIE())});_IG_AddModuleEventHandler(a,"unmaximize",function(){ig_eb(a)})}var _IG_FR_listOfFeeds=[];function ig_I(a){var b;b=a;var c;if(window.ActiveXObject){c=new ActiveXObject("Microsoft.XMLDOM");c.async=ig_c;c.validateOnParse=ig_c;c.resolveExternals=ig_c;c.loadXML(b)}else{c=new DOMParser;c=c.parseFromString(b,"text/xml")}b=c;if((c=b.documentElement)&&c.nodeName=="parsererror"||navigator.userAgent.indexOf("Safari")>=0&&_gelstn("parsererror",b)[0])return a;return b}var ig_fb=(new Date).getTime();
function ig_gb(a){if(!a.bf&&!a.headers&&window._pl_data&&_pl_data[a.url]&&!(!isNaN(a.refreshInterval)&&a.refreshInterval>=0&&(new Date).getTime()>ig_fb+a.refreshInterval*1E3))if(a.Sa){var b=ig_I(_pl_data[a.url]);a.callback(b)}else a.callback(_pl_data[a.url]);else{b="/ig/jsonp?";if(_et!="")b+="et="+_et+"&";if(!isNaN(a.refreshInterval)&&a.refreshInterval>=0)b=_appendMaxAgeParameter(b,a.refreshInterval);if(a.encoding)b+="enc="+_esc(a.encoding)+"&";if(a.headers){for(var c=[],d=0;d<a.headers.length;d++)c.push(_esc(a.headers[d][0]+
":"+a.headers[d][1]));b+="hdrs="+_esc(c.join(","))+"&"}b+="url="+_esc(a.url);_sendx(b,function(e){var f=e,h=a.url;e=a.callback;var g=a.Sa;if(!f||f==""||f.length<=27||f.charAt(27)!="{")e(g?ig_:"");else{f=eval("("+f.substring(27)+")");if(h in f){h=f[h].body;e(g?ig_I(h):h)}}},ig_c,a.bf)}}function ig_hb(a){var b={};for(var c in a)b[c]=a[c];return b}function _IG_FetchContent(a,b,c){c=c!=ig_&&typeof c=="object"?ig_hb(c):{};c.url=a;c.callback=b;c.Sa=ig_c;ig_gb(c)}
function _IG_FetchXmlContent(a,b,c){c=c!=ig_&&typeof c=="object"?ig_hb(c):{};c.url=a;c.callback=b;c.Sa=ig_b;ig_gb(c)}function ig_ib(a,b,c){_IG_FetchContent(a,function(d){if(d){d=ig_I(d);if(typeof d=="object"&&d.firstChild){var e=d.firstChild;e.nodeType==7&&e.nodeName=="xml"&&d.removeChild(e);b(d);return}}b(ig_)},c)}function ig_jb(a,b){var c="/ig/feedjson";_sendx(c,function(d){var e={};try{e=eval("("+d.slice(27)+")")}catch(f){e={}}for(var h in b){d=e[h]?e[h]:ig_;b[h](d)}b=ig_},ig_c,a)}
var ig_kb=ig_c,ig_lb=0,ig_J="",ig_K={};function _IG_FetchFeedAsJSON(a,b,c,d,e){if(typeof e!="object")e={};var f="fr_"+ig_lb++;a="url="+_esc(a);if(!isNaN(e.refreshInterval)&&e.refreshInterval>=0)a=_appendMaxAgeParameter(a,e.refreshInterval);if(c)a+="&val="+_esc(c);if(d)a+="&sum=1";c=f+"="+_esc(a);if(ig_kb){d={};d[f]=b;ig_jb(c,d)}else{if(ig_J!="")ig_J+="&";ig_J+=c;ig_K[f]=b}}function ig_mb(){ig_kb=ig_b;ig_J!=""&&ig_jb(ig_J,ig_K);ig_J="";ig_K=ig_}_IG_AddEventHandler("domload",ig_mb);
_exportSymbols("google.gadgets.Fetchers",["getContent",_IG_FetchContent,"getXMLContent",ig_ib,"getFeedAsJSON",_IG_FetchFeedAsJSON]);function ig_nb(a,b,c){var d=ig_u("m",b);if(d)d.ti=a;var e=_gel("m_"+b+"_title");if(e)e.innerHTML=_hesc(a);if(e=_gel("left_nav_m_"+b+"_title"))if(e=e.firstChild){e.title=a;e.innerHTML=_hesc(a);c||(e.offsetWidth==0?_IG_RegisterOnloadHandler(function(){ig_L(e)}):ig_L(e))}}
function ig_L(a,b){b=b||121;var c=a.title;if(!(a.offsetWidth<=b)){var d=0,e=c.length,f,h=c.match(/\(\d+\)$/);if(h=h?h[0]:""){h=" "+h;e=c.length-h.length;f=5*h.length;if(f>b>>1)h=""}for(;f=e-d>>1;){f=d+f;a.innerHTML=ig_ob(c,f,h);if(a.offsetWidth>b)e=f;else d=f}a.innerHTML=ig_ob(c,d,h)}}function ig_ob(a,b,c){a=[a.substring(0,b),"..."];c&&a.push(c);return _hesc(a.join(""))}function ig_M(a){return typeof a=="undefined"||!a||a=="undefined"}function ig_pb(a,b){ig_M(a)||ig_nb(b,_ig_gmid_(a))}
_IFPC.registerService("set_title",ig_pb);function _IG_SetTitle(a,b,c){if(ig_M(b))ig_a(new Error("Inline modules must specify their __MODULE_ID__ when using _IG_SetTitle"));else ig_nb(a,b,c)}
function _IG_SetTitleDir(a,b){if(ig_M(b))ig_a(new Error("Inline modules must specify their __MODULE_ID__ when using _IG_SetTitleDir"));else{var c=ig_u("m",b);if(c)if(a)c.ti_dir=a;else delete c.ti_dir;if(c=_gel("m_"+b+"_title"))a?c.setAttribute("dir",a):c.removeAttribute("dir");if(c=_gel("left_nav_m_"+b+"_title"))a?c.setAttribute("dir",a):c.removeAttribute("dir")}}
function _IG_FormatLeftNavTitles(){_IG_RegisterOnloadHandler(function(){var a=_gel("full_nav"),b=_gelsbyregex("div",/^left_nav_m_\d+_title$/,a);if(b)for(a=0;a<b.length;++a){var c=b[a];(c=c.firstChild)&&ig_L(c)}for(a=0;a<_IG_MD.dt.length;++a)if(c=_gel("tab"+_IG_MD.dt[a].i+"_view_title")){b=c.className=="selected_tab_view_title"?80:100;(c=c.firstChild)&&ig_L(c,b)}})};function _delpromobox(){_xsetp("hp=0");var a=_gel("promobox");a.parentNode.removeChild(a);return ig_c}function _delmessage(){_xsetp("gm=0");var a=_gel("googlemessage");a.parentNode.removeChild(a);return ig_c}function _delpromomod(){_xsetp("pm=0");var a=_gel("promomod");a.parentNode.removeChild(a);return ig_c};var ig_N=new (function(){this.da={};var a=window.onbeforeunload;window.onbeforeunload=function(){a&&a();ig_N.Qe()}});ig_N.ud=function(a,b){this.da[a]=b};ig_N.lf=function(a){delete this.da[a]};ig_N.Y=function(a){return this.da[a]};ig_N.Qe=function(){var a=[];for(var b in this.da)a.push(b+"="+this.da[b]);if(a.length){b=ig_m();a="/ig/setp?et="+_et+"&"+a.join("&");b.open("GET",a,ig_c);b.send(ig_)}};function _IG_add_setp_parameter_onbeforeunload(a,b){ig_N.ud(a,b)}
function _IG_remove_setp_parameter_onbeforeunload(a){ig_N.lf(a)}function _IG_get_setp_parameter_onbeforeunload(a){return ig_N.Y(a)};var ig_O={Oa:0,Gb:1,Kb:2,Cb:3},ig_P=function(){function a(){var i=[],o=[];for(var p in j)if(j[p]&&!k[p])i.push(p);else!j[p]&&k[p]&&o.push(p);i.length?_IG_add_setp_parameter_onbeforeunload("exptabs",i.join(":")):_IG_remove_setp_parameter_onbeforeunload("exptabs");o.length?_IG_add_setp_parameter_onbeforeunload("coltabs",o.join(":")):_IG_remove_setp_parameter_onbeforeunload("coltabs");_IG_add_setp_parameter_onbeforeunload("roster",l+"")}function b(i){_gel("gadget_set"+i).style.display="block";_gel("triangle"+
i).className="v2minbox";j[i]=ig_b;_sendx("/ig/ui?xp=v2&action=expandTab&t="+i,ig_,ig_c,ig_)}function c(i){_gel("gadget_set"+i).style.display="none";_gel("triangle"+i).className="v2maxbox";j[i]=ig_c;_sendx("/ig/ui?xp=v2&action=collapseTab&t="+i,ig_,ig_c,ig_)}function d(){m.style.display="none";n.style.display="none";switch(e){case ig_O.Oa:var i=_gel("section"+f+"_contents");i.className="section_contents leftunselectedtab leftborder";_gel("tab"+f).className="section_title unselected_section_title";
_gel("tab_separator"+f).style.display="";if(h)_gel("tab_separator"+h).style.display="";else if(_gel("tab_separator_bot"))_gel("tab_separator_bot").style.display="";break;case ig_O.Gb:i=_IG_getCurrentMaxId();i=_gel("left_nav_m_"+i+"_title");i.className="gadget_title";break;case ig_O.Kb:i=_gel("updates_left_nav");i.className="gadget_title";break;case ig_O.Cb:i=_gel("shares_left_nav");i.className="gadget_title";break}}var e=ig_O.Oa,f=ig_,h=ig_,g={},k={},j={},l=ig_b,m=ig_,n=ig_;return{De:function(){m=
_gel("left_nav_top_rounded_corners");n=_gel("left_nav_bottom_rounded_corners")},zf:function(i){f=i},qg:function(i){e=i},me:function(){return f},yf:function(){for(var i=_gel("section"+f+"_contents").nextSibling;i;){if(i.id&&i.id.match(/section\d+_contents/)){h=i.id.match(/\d+/);break}i=i.nextSibling}},tg:function(){d()},rc:function(i){d();i=_gel("left_nav_m_"+i+"_title");i.className="selected_gadget_title gadget_title leftselectedtab surroundborder";m.style.display="";n.style.display="";i.parentNode.insertBefore(m,
i);i.parentNode.insertBefore(n,i.nextSibling);e=ig_O.Gb},sc:function(){d();var i=_gel("section"+f+"_contents");i.className="selected_section_contents leftselectedtab surroundborder";_gel("tab"+f).className="section_title selected_section_title";_gel("tab_separator"+f).style.display="none";if(h)_gel("tab_separator"+h).style.display="none";else if(_gel("tab_separator_bot"))_gel("tab_separator_bot").style.display="none";m.style.display="";n.style.display="";i.parentNode.insertBefore(m,i);i.parentNode.insertBefore(n,
i.nextSibling);e=ig_O.Oa},Ae:function(){d();var i=_gel("shares_left_nav");i.className="selected_gadget_title gadget_title leftselectedtab surroundborder";m.style.display="";n.style.display="";i.parentNode.insertBefore(m,i);i.parentNode.insertBefore(n,i.nextSibling);e=ig_O.Cb},Be:function(){d();var i=_gel("updates_left_nav");i.className="selected_gadget_title gadget_title leftselectedtab surroundborder";m.style.display="";n.style.display="";i.parentNode.insertBefore(m,i);i.parentNode.insertBefore(n,
i.nextSibling);e=ig_O.Kb},Of:function(i){var o=_gel("m_"+i+"_home_menu");if(o)o.style.display="none";if(i=_gel("m_"+i+"_canvas_menu"))i.style.display=""},Pf:function(i){var o=_gel("m_"+i+"_canvas_menu");if(o)o.style.display="none";if(i=_gel("m_"+i+"_home_menu"))i.style.display=""},xe:function(i){if(i=_gel("left_nav_"+i+"_title"))i.style.display="none"},Ff:function(i){if(i=_gel("left_nav_"+i+"_title"))i.style.display=""},Gc:function(i){var o=_gel("m_"+i+"_b");g[i]=o&&o.style.display=="none";i=!_gel("remote_iframe_"+
i);var p=ig_b;o.style.display=i&&p?"none":""},Hc:function(i){var o=_gel("m_"+i+"_b");o.style.display=g[i]?"none":""},Hf:function(){if(f!="0"){_gel("rcbg").style.display="";_gel("col2").className="botborder"}},Wc:function(){if(f=="0"){_gel("rcbg").style.display="";_gel("col2").className="botborder"}},qc:function(){if(f=="0"){_gel("rcbg").style.display="none";_gel("col2").className="topbotborder"}},Xd:function(i){k[i]=ig_b;j[i]=ig_b},Jd:function(i){k[i]=ig_c;j[i]=ig_c},Rf:function(i,o){if(!i)i=window.event;
i.cancelBubble=ig_b;i.stopPropagation&&i.stopPropagation();_gel("gadget_set"+o).style.display=="none"?b(o):c(o);a()},Qf:function(){if(_gel("talk_container")){l=!l;_gel("roster_triangle").className=l?"v2minbox":"v2maxbox";if(window.gTalkNotifier&&window.gTalkNotifier._setRosterExpanded)window.gTalkNotifier._setRosterExpanded(l);else _gel("talk_container").style.display=l?"":"none";_log("roster_toggle:"+(l?"1":"0"));a()}},rf:function(i){l=i},Je:function(){return l},ye:function(i){if(i=_gel(i))i.style.display=
"none"},Zc:function(i){var o=_gel("DD_"+i+"_zip");if(o){i=(i=_gel("m_"+i+"_b"))&&i.style.display=="none";o.innerHTML=i?IG_MSGS.MAXG:IG_MSGS.MING}},Yc:function(i){var o=_gel("m_"+i+"_b");i=o&&o.style.display=="none";if((o=o.nextSibling)&&o.className)o.className=i?"rnd_modtitle":"rnd_modboxin"}}}();
function _IG_LN_init(a){_IG_AddEventHandler("modulemaximize",ig_P.rc);_IG_AddEventHandler("modulemaximize",ig_P.Of);_IG_AddEventHandler("modulemaximize",ig_P.Gc);_IG_AddEventHandler("modulemaximize",ig_P.Wc);_IG_AddEventHandler("moduleunmaximize",ig_P.sc);_IG_AddEventHandler("moduleunmaximize",ig_P.Pf);_IG_AddEventHandler("moduleunmaximize",ig_P.Hc);_IG_AddEventHandler("moduleunmaximize",ig_P.qc);_IG_AddEventHandler("moduledelete",ig_P.xe);_IG_AddEventHandler("moduleundelete",ig_P.Ff);_IG_AddEventHandler("modulezip",
ig_P.Zc);_IG_AddEventHandler("modulezip",ig_P.Yc);_IG_AddEventHandler("moduleunzip",ig_P.Zc);_IG_AddEventHandler("moduleunzip",ig_P.Yc);_IG_RegisterOnloadHandler(ig_P.yf);_IG_RegisterOnloadHandler(ig_P.Hf);_IG_RegisterOnloadHandler(ig_P.De);ig_P.zf(a)}
var _IG_get_selected_tab_id=ig_P.me,_IG_expand_tab_onload=ig_P.Xd,_IG_collapse_tab_onload=ig_P.Jd,_IG_toggle_tab=ig_P.Rf,_IG_toggle_roster=ig_P.Qf,_IG_roster_state_onload=ig_P.rf,_IG_is_roster_expanded=ig_P.Je,_IG_hide_promo=ig_P.ye,_IG_maybe_unzip_module=ig_P.Gc,_IG_maybe_zip_module=ig_P.Hc,_IG_hideRoundedCornerOnRestore=ig_P.qc,_IG_showRoundedCornerOnMaximize=ig_P.Wc,_IG_highlight_invites=ig_P.Ae,_IG_highlight_updates=ig_P.Be,_IG_highlight_module=ig_P.rc,_IG_highlight_tab=ig_P.sc;
