#!/bin/sh

cd `dirname $0`

for file in *.js
do
  echo "Running on $file"
  base=`echo $file | cut -d'.' -f1`
  env="$base.env"
  result=`../../tcg -env $env -tc $file 2>&1`
  if [ $? -ne 0 ]; then
      echo "$file: aborted with exit code $?; output was:\n$result\n"
  fi
done
