#!/bin/bash

verbose=""
if [ "$1" = "-verbose-errors" ] ; then
  verbose="-verbose-errors"
  shift
fi

../run $verbose -env ../data/javascript2.env -newidl ../data/all-idls.idl -newidl ../data/typedef-overrides.idl -compile-env -allow-unbound "ref Ext" "$@"
